ButterBS = designfilt('bandstopiir', ...
    'PassbandFrequency1',45, ...
    'StopbandFrequency1',48, ...
    'StopbandFrequency2',52, ...
    'PassbandFrequency2',55, ...
    'PassbandRipple1',1, ...
    'StopbandAttenuation',60, ...
    'PassbandRipple2',1, ...
    'SampleRate',256);
ButterHP = designfilt('highpassiir', ...
    'StopbandFrequency',1, ...
    'PassbandFrequency',2, ...
    'StopbandAttenuation',60, ...
    'PassbandRipple',1, ...
    'SampleRate',256);