ButterBS = designfilt('bandstopiir', ...
    'PassbandFrequency1',45, ...
    'StopbandFrequency1',48, ...
    'StopbandFrequency2',52, ...
    'PassbandFrequency2',55, ...
    'PassbandRipple1',1, ...
    'StopbandAttenuation',60, ...
    'PassbandRipple2',1, ...
    'SampleRate',256);
ButterHP = designfilt('highpassiir', ...
    'StopbandFrequency',0.5, ...
    'PassbandFrequency',2, ...
    'StopbandAttenuation',30, ...
    'PassbandRipple',1, ...
    'SampleRate',256);
%{ 
ButterBP = designfilt('bandpassiir', ...
    'StopbandFrequency1',0.5, ...
    'PassbandFrequency1',2, ...
    'PassbandFrequency2',40, ...
    'StopbandFrequency2',50, ...
    'StopbandAttenuation1',40, ...
    'PassbandRipple',1, ...
    'StopbandAttenuation2',40, ...
    'SampleRate',256);
%}
load("FC.mat")
load("FADHD.mat")
load("MADHD.mat")
load("MC.mat")